In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_selection import SelectKBest, chi2
import numpy as np

In [2]:
df = pd.read_csv('bhutan_fuel_prices.csv')

In [3]:
df

,Region,Product,Company,Approved_Date,Station,RSP/KL,RSP/L
0,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,2022-04-01,Phuentsholing,98497.76,98.50
1,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,2022-04-01,Rinchending,98578.22,98.58
2,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,2022-04-01,Pasakha,98631.86,98.63
3,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,2022-04-01,Chimakothi,100206.55,100.21
4,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,2022-04-01,Lungtenzampa,100650.06,100.65
...,...,...,...,...,...,...,...
11373,Central Region,MS (in KL),Indian Oil Corporation Limited,2020-05-06,Lhamoizingkha,41066.04,41.07
11374,Central Region,MS (in KL),Indian Oil Corporation Limited,2020-05-06,Dangdung,43467.67,43.47
11375,Central Region,MS (in KL),Indian Oil Corporation Limited,2020-05-06,Panbang,41612.49,41.61
11376,Central Region,MS (in KL),Indian Oil Corporation Limited,2020-05-06,Tingtibi,41222.56,41.22
11377,,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df.drop('Approved_Date', axis = 1)

In [5]:
df

,Region,Product,Company,Station,RSP/KL,RSP/L
0,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Phuentsholing,98497.76,98.50
1,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Rinchending,98578.22,98.58
2,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Pasakha,98631.86,98.63
3,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Chimakothi,100206.55,100.21
4,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Lungtenzampa,100650.06,100.65
...,...,...,...,...,...,...
11373,Central Region,MS (in KL),Indian Oil Corporation Limited,Lhamoizingkha,41066.04,41.07
11374,Central Region,MS (in KL),Indian Oil Corporation Limited,Dangdung,43467.67,43.47
11375,Central Region,MS (in KL),Indian Oil Corporation Limited,Panbang,41612.49,41.61
11376,Central Region,MS (in KL),Indian Oil Corporation Limited,Tingtibi,41222.56,41.22
11377,,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df.drop('RSP/KL', axis=1)

In [7]:
df

,Region,Product,Company,Station,RSP/L
0,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Phuentsholing,98.50
1,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Rinchending,98.58
2,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Pasakha,98.63
3,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Chimakothi,100.21
4,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Lungtenzampa,100.65
...,...,...,...,...,...
11373,Central Region,MS (in KL),Indian Oil Corporation Limited,Lhamoizingkha,41.07
11374,Central Region,MS (in KL),Indian Oil Corporation Limited,Dangdung,43.47
11375,Central Region,MS (in KL),Indian Oil Corporation Limited,Panbang,41.61
11376,Central Region,MS (in KL),Indian Oil Corporation Limited,Tingtibi,41.22
11377,,NaN,NaN,NaN,NaN

In [8]:
df.isna().sum()

Region      0
Product     1
Company    16
Station    30
RSP/L       1
dtype: int64

In [9]:
df.dtypes

Region      object
Product     object
Company     object
Station     object
RSP/L      float64
dtype: object

In [10]:
df['price'] = df['RSP/L']

In [11]:
df

,Region,Product,Company,Station,RSP/L,price
0,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Phuentsholing,98.50,98.50
1,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Rinchending,98.58,98.58
2,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Pasakha,98.63,98.63
3,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Chimakothi,100.21,100.21
4,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Lungtenzampa,100.65,100.65
...,...,...,...,...,...,...
11373,Central Region,MS (in KL),Indian Oil Corporation Limited,Lhamoizingkha,41.07,41.07
11374,Central Region,MS (in KL),Indian Oil Corporation Limited,Dangdung,43.47,43.47
11375,Central Region,MS (in KL),Indian Oil Corporation Limited,Panbang,41.61,41.61
11376,Central Region,MS (in KL),Indian Oil Corporation Limited,Tingtibi,41.22,41.22
11377,,NaN,NaN,NaN,NaN,NaN

In [12]:
df = df.drop('RSP/L', axis = 1)

In [13]:
df

,Region,Product,Company,Station,price
0,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Phuentsholing,98.50
1,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Rinchending,98.58
2,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Pasakha,98.63
3,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Chimakothi,100.21
4,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Lungtenzampa,100.65
...,...,...,...,...,...
11373,Central Region,MS (in KL),Indian Oil Corporation Limited,Lhamoizingkha,41.07
11374,Central Region,MS (in KL),Indian Oil Corporation Limited,Dangdung,43.47
11375,Central Region,MS (in KL),Indian Oil Corporation Limited,Panbang,41.61
11376,Central Region,MS (in KL),Indian Oil Corporation Limited,Tingtibi,41.22
11377,,NaN,NaN,NaN,NaN

In [14]:
 df.dropna(subset=['price'],inplace=True)

In [15]:
df.isna().sum()

Region      0
Product     0
Company    15
Station    29
price       0
dtype: int64

In [16]:
x = df.drop('price',axis =1)

In [17]:
x

,Region,Product,Company,Station
0,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Phuentsholing
1,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Rinchending
2,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Pasakha
3,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Chimakothi
4,Western Region,HSD (in KL),Bharat Petroleum Corporation Limited,Lungtenzampa
...,...,...,...,...
11372,Central Region,MS (in KL),Indian Oil Corporation Limited,Dagana
11373,Central Region,MS (in KL),Indian Oil Corporation Limited,Lhamoizingkha
11374,Central Region,MS (in KL),Indian Oil Corporation Limited,Dangdung
11375,Central Region,MS (in KL),Indian Oil Corporation Limited,Panbang
11376,Central Region,MS (in KL),Indian Oil Corporation Limited,Tingtibi

In [18]:
y = df['price']

In [19]:
y

0         98.50
1         98.58
2         98.63
3        100.21
4        100.65
          ...
11372     42.16
11373     41.07
11374     43.47
11375     41.61
11376     41.22
Name: price, Length: 11377, dtype: float64

In [20]:
xtrain,ytrain,xtest,ytest = train_test_split(x,y, test_size=0.2,random_state=5,shuffle=True)

In [21]:
# n_transformer = Pipeline(steps = [
#     ('impute_n ', SimpleImputer(fill_value='missing',strategy='mean')),
  
# ])

In [22]:
pl = Pipeline([
    #('impute',SimpleImputer(missing_values=np.nan, strategy='mean')),
     ('imput',SimpleImputer(missing_values=np.nan, strategy='most_frequent')),
    
    
    ('one', OneHotEncoder(sparse =False,handle_unknown='ignore')),
    ('scaler' , StandardScaler()),
   
    ('ir_classifier', DecisionTreeClassifier())
])

In [47]:

pl2 = Pipeline([
    
    ('imput',SimpleImputer(missing_values=np.nan, strategy='most_frequent')),
    
    ('one', OneHotEncoder(sparse = False,handle_unknown='ignore')),
    ('scaler2', StandardScaler()),
   
    ('ir_classifier2',LogisticRegression(random_state=0))
])

In [48]:
pipelines = [pl,pl2]
pipedict = {0:'DicisionTree',1:'LogisticRegression'}

In [49]:
for pipe in pipelines:
    pipe.fit(xtrain,ytrain)

ValueError: Input contains NaN

In [269]:
for i,model in enumerate(pipelines):
    print('{} Test Accuracy: {}'.format(pipedict[i],model.score(xtest,ytest)))

ValueError: Expected 2D array, got 1D array instead:
array=[73.06 84.47 63.07 ... 67.18 96.16 76.75].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [218]:
processer = ColumnTransformer(
    transformers=[
    ('c_trans', c_transformer, [0,1,2,3])]
    
    
)

In [219]:
dmtl = DecisionTreeRegressor()

In [220]:
test_model = Pipeline( steps =[
    ('pre',processer),
    ('model', dmtl)
])

In [227]:
xtrain = xtrain.values
ytrain = ytrain.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [228]:
test_model.fit(xtrain,ytrain)

ValueError: Input contains NaN